name: Build & Test Backend
run-name: ${{ github.actor }} is building and testing the back-end 🚀
on:
  pull_request:
    types:
    - opened
    branches:
    - 'main'
jobs:
  #CI
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
      # Back
      - name: Setup backend
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven
      - name: Test backend
        working-directory: ./back
        run: mvn --batch-mode --update-snapshots clean verify
      # Front
      - run: echo "Testing frontend..."
      - name: Setup frontend
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: front/package-lock.json
          node-version: '16'
          cache: 'npm'
      - name: Test frontend
        working-directory: ./front
        run: |
          npm install
          npm run coverage
      # SonarQube
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #CD
  deploy-docker-images:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # Checkout
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}
      # Docker Login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Front container
      - name: Build and push front-end image
        uses: docker/build-push-action@v6
        with:
          context: front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
      # Back container
      - name: Build and push back-end image
        uses: docker/build-push-action@v6
        with:
          context: back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest